double a, b, c, d, x, y, z, r;
Console.WriteLine("Задайте значення а:");
a = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення b:");
b = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення c:");
c = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення d:");
d = double.Parse(Console.ReadLine());
x = (a+2*b-c+d)/c*d+(a+b)/(c-d)-a*a/(b*b);
Console.WriteLine("Значення x:");
Console.WriteLine(x);
y = 5 * (a + b) * (c - d) / 1.0 / 2 * c + d * d * ((a * a - b * b) / (b - a));
Console.WriteLine("Значення y:");
Console.WriteLine(y);
z = (Math.Pow((x * x - 2 * x), 3) - 4 * (Math.Pow(x, 4) + 1)) * (1 - b) / (5 * a + 3 * b);
Console.WriteLine("Значення z:");
Console.WriteLine(z);
r = (1.0 / 2 * a + 3.0 / 4 * b - 7.0 / 5) / (3 * c + 1) + 1 / (a - c);
Console.WriteLine("Значення r:");
Console.WriteLine(r);