double a, b, m, n, x, y, z1,z2;
Console.WriteLine("Задайте значення а:");
a = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення b:");
b = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення m:");
m = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення n:");
n = double.Parse(Console.ReadLine());
Console.WriteLine("Задайте значення x:");
x = double.Parse(Console.ReadLine());
z1 = ((m - 1) * Math.Sqrt(m) - (n - 1) * Math.Sqrt(n)) / (Math.Sqrt(m * m * m * n) + n * m + m * m - m);
Console.WriteLine($"z1 = {z1}");
z2 = (Math.Sqrt(m) - Math.Sqrt(n)) / m;
Console.WriteLine($"z2 = {z2}");
y = 2.4 * Math.Abs((x * x + b) / a) + (a - b) * Math.Sin(a - b) * Math.Sin(a - b) + Math.Pow(10, -2) * (x - b);
Console.WriteLine($"y = {y}");